### PR TITLE
Add Dockerfile for arm

### PR DESCRIPTION
**Pull request by paul-nameless**
Hello,

Recently I wanted to install fishnet on arm server with docker and came out with this Dockerfile.

Would like to share if it will be helpful for somebody.

### CODE REVIEW

**Comment by toughIQ** [comment]
I really like the idea of an ARM image.
But would we need a dedicated Dockerfile?
Wouldnt one file be enough and we do a `multiarch` build?
I assume this approach is based on the fact, that the current `fishnet-builder` image is not ARM, right?

**Comment by paul-nameless** [comment]
Yeah, the fishnet-builder image is not arm. Maybe if it will be arm we can use one dockerfile. I had some problems with alpine:3 on arm (probably some musl incompatibilities)

**Comment by toughIQ** [comment]
What I understand from your new approach:
1. we dont need a dedicated `fishnet-builder` image, since we use a preconfigured `rust` container as _builder_
2. we would rebase the image from `alpine` to `debian` which results in a bigger image size. Approx. 40MB vs 120MB

**Comment by toughIQ** [comment]
Hi @paul-nameless 
I just took your ARM Dockerfile, added my recent changes regarding file permissions and created a multiarch amd64&arm64 build.
To me it looks quite good.
Tested amd64 on my Notebook and deployed the ARM version in an AWS ARM OpenShift cluster...both work fine.

MultiArch image can be fetched and tested from here: `docker.io/toughiq/fishnet:multi`

**Comment by niklasf** [comment]
> we dont need a dedicated fishnet-builder image, since we use a preconfigured rust container as builder

That's ok for ARM, but not good on x86-64, so also not good for a multi-arch container. The purpose of [fishnet-builder](https://github.com/lichess-org/fishnet-builder/blob/main/Dockerfile) is to enable profile-guided optimization for various instruction set extensions. Without that, everything will work, but will not be as fast as it could be on the best available hardware.

**Comment by paul-nameless** [comment]
Tested your image `docker.io/toughiq/fishnet:multi`, works great on my server 👍

**Comment by toughIQ** [comment]
Hi @niklasf 
so I assume we need multiple ways of building for different architectures.
I think there is a way of describing the different build strategies within one single Dockerfile.
https://docs.docker.com/build/building/multi-platform/

I am currently not sure, if this approach is the best one, since it would make the Dockerfile more complex.

**Comment by toughIQ** [comment]
OK...I think I misunderstood the `platform` stuff.
The `--platform` parameter with `FROM` just defines, what image, if multiarch is present, to use. 
It is not some kind of switch, so we could say: "on ARM use the `rust` image, on amd64 use `fishnet-builder`.
So I think the approach should be this:
Different `Dockerfile` setups, using each according to the platform and putting the resulting images in one multiarch `manifest`.

**Comment by niklasf** [comment]
Without having seen everything it entails, I think I prefer the multi-arch approach. It makes the Dockerfile more complex, but in turn seems easier for users.

**Comment by yonailo** [comment]
+1 to have a solution for this, I would like to have an official way of installing fisnet through docker on my Raspberry PI 400 ;)

**Comment by niklasf** [comment]
I now updated fishnet-builder and the CI pipeline with the multi-arch approach. The result is available at `niklasf/fishnet:master` (which is always the latest successful pipeline run).

**Pull request closed without merging**
